name: build-neoforge-1-21-1

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-cleanup: always

      - name: Build neoforge
        run: ./gradlew :neoforge:build --configure-on-demand

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sable-neoforge-1.21.1
          path: neoforge/build/libs/*.jar
